apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  # namespace: monitoring  # Ensure this is the correct namespace
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s

    scrape_configs:
      - job_name: 'flask-app'
        metrics_path: '/metrics'
        static_configs:
          - targets: ['flask-app:5200']  # Replace with your app's hostname/IP
      